server:
  port: 8081
spring:
  application:
    name: acount
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 106.14.157.166:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.157.166:3306/data?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ENC(QgMFhSYEGAS7e3pa08jAhhjivCA1iG5d)

  redis:
    client-type: jedis
    host: 140.143.141.194
    password: redispsw
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60000
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        connectionTimeoutMilliseconds: 30000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idleTimeoutMilliseconds: 60000
        jdbc-url: jdbc:mysql://106.14.157.166:3306/data?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        maintenanceIntervalMilliseconds: 30000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 50
        password: ENC(QgMFhSYEGAS7e3pa08jAhhjivCA1iG5d)
        type: com.zaxxer.hikari.HikariDataSource
        username: root
    props:
      # 打印执行的数据库以及语句
      sql:
        show: true
    sharding:
      tables:
        traffic:
          # 指定traffic表的数据分布情况，配置数据节点,行表达式标识符使用 ${...} 或 $->{...}，但前者与 Spring 本身的文件占位符冲突，所以在 Spring 环境中建议使用 $->{...}
          actual-data-nodes: ds0.traffic_$->{0..1}
          # 水平分表策略+行表达式分片
          table-strategy:
            inline:
              algorithm-expression: traffic_$->{account_no % 2}
              sharding-column: account_no
          #id生成策略
          key-generator:
            column: id
            props:
              worker:
                id: ${workerId}
            #id生成策略
            type: SNOWFLAKE


#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


sms:
  app-code: 1ab6e5a9091f4614b0c995e4cb71297e
  app-secret: fehuNmtCmTVt8tYb1ySGsEDg1KOFMU3h
  template-id: M72CB42894


#阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucketname: cyx-short-link